@echo off
echo Preparando...
git add .
echo Confirmando...
git commit -m "Auto-commit: Actualizacion"
echo Trayendo cambios...
git pull origin main --rebase
echo Subiendo...
git push origin main
echo Completado!
pause
